spring:
  application:
    name: aang
  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    username: username        # H2 DB ?? ID (??? ??)
    password: password        # H2 DB ?? PW (??? ??)

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??
